---
AWSTemplateFormatVersion: "2010-09-09"
Description: AWS CloudFormation template to create the messages stack
Parameters:
  ExternalId:
    Type: String
    Description: "The external ID to use in the user permissions policy"
Resources:
  MessagesDdbTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "messages"
      AttributeDefinitions:
        - AttributeName: "messageId"
          AttributeType: "S"
        - AttributeName: "content"
          AttributeType: "S"
        - AttributeName: "createdAt"
          AttributeType: "N"
        - AttributeName: "createdBy"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "messageId"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: "sortByDateCreated"
          KeySchema:
            - AttributeName: "messageId"
              KeyType: "HASH"
            - AttributeName: "createdAt"
              KeyType: "RANGE"
          Projection:
            NonKeyAttributes:
              - "content"
              - "createdBy"
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: "0"
            WriteCapacityUnits: "0"

  MessagesAccessUser:
    Type: AWS::IAM::User
    Properties:
      UserName: "messages-dude"
      Policy:
        PolicyName: "message-dude-policy"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Sid: AllowAssumingParticularRole
              Effect: Allow
              Action: sts:AssumeRole
              Resource: !Ref MessagesAppRole
            - Sid: AllowGetCallerIdentity
              Effect: Allow
              Action: sts:GetCallerIdentity
              Resource: "*"
