---
AWSTemplateFormatVersion: "2010-09-09"
Description: AWS CloudFormation template to create the messages stack
Parameters:

Resources:
  myDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "messages"
      AttributeDefinitions:
        - AttributeName: "messageId"
          AttributeType: "S"
        - AttributeName: "content"
          AttributeType: "S"
        - AttributeName: "createdAt"
          AttributeType: "N"
        - AttributeName: "createdBy"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "messageId"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: "sortByDateCreated"
          KeySchema:
            - AttributeName: "messageId"
              KeyType: "HASH"
            - AttributeName: "createdAt"
              KeyType: "RANGE"
          Projection:
            NonKeyAttributes:
              - "content"
              - "createdBy"
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: "0"
            WriteCapacityUnits: "0"
