---
AWSTemplateFormatVersion: "2012-10-17"
Description: AWS CloudFormation template to create the messages stack
Parameters:
  ExternalId:
    Type: String
    Description: "The external ID to use in the user permissions policy"
Resources:
  MessagesDdbTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "messages"
      AttributeDefinitions:
        - AttributeName: "messageId"
          AttributeType: "S"
        - AttributeName: "content"
          AttributeType: "S"
        - AttributeName: "createdAt"
          AttributeType: "N"
        - AttributeName: "createdBy"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "messageId"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: "sortByDateCreated"
          KeySchema:
            - AttributeName: "messageId"
              KeyType: "HASH"
            - AttributeName: "createdAt"
              KeyType: "RANGE"
          Projection:
            NonKeyAttributes:
              - "content"
              - "createdBy"
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: "0"
            WriteCapacityUnits: "0"

  MessagesAppPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: "MessagesAppPolicy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AllowListTablesAndLimits"
            Effect: Allow
            Action:
              - dynamodb:ListTables
              - dynamodb:DescribeLimits
            Resource: "*"
          - Sid: "AllowTableActions"
            Effect: Allow
            Action:
              - dynamodb:BatchGetItem
              - dynamodb:BatchWriteItem
              - dynamodb:ConditionCheckItem
              - dynamodb:PutItem
              - dynamodb:DescribeTable
              - dynamodb:DeleteItem
              - dynamodb:GetItem
              - dynamodb:Scan
              - dynamodb:Query
              - dynamodb:UpdateItem
              - dynamodb:UpdateTable
            Resource: !GetAtt MessagesDdbTable.Arn
          - Sid: "AllowTableActions"
            Effect: Allow
            Action:
              - dynamodb:Scan
              - dynamodb:Query
              - dynamodb:GetRecords
            Resource:
              - !Sub "${MessagesDdbTable.Arn}/stream/*"
              - !Sub "${MessagesDdbTable.Arn}/index/*"

  MessagesAccess:
    Type: AWS::IAM::Role
    Properties:
      PolicyName: messages-app-role
      Description: "a role meant to access the messages table"
      MaxSessionDuration: 3600
      ManagedPolicyArns: !Sub "arn:aws:iam::${AWS::AccountId}:policy/${MessagesAppPolicy}"

  MessagesAccessUser:
    Type: AWS::IAM::User
    Properties:
      UserName: "messages-dude"
      Policy:
        PolicyName: "message-dude-policy"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Sid: AllowAssumingParticularRole
              Effect: Allow
              Action: sts:AssumeRole
              Resource: !Ref MessagesAppRole
            - Sid: AllowGetCallerIdentity
              Effect: Allow
              Action: sts:GetCallerIdentity
              Resource: "*"
